### ISSUE TITLE
Proxy option

### ISSUE THREAD

**Issue by waclock** [AaronTraas/pyroyale#8]
Hello, 
I was using crtools version 1.15.14 and had monkeypatched the api clased with something like this:
```
    def __api_call(self, endpoint):
        # Make request and handle errors. If request returns a valid object,
        # return that object.
        proxyDict = {
            "http": os.environ.get('FIXIE_URL', ''),
            "https": os.environ.get('FIXIE_URL', '')
        }
        r = requests.get(self.baseurl + endpoint,
                         headers=self.headers, proxies=proxyDict)

        if r.status_code == 200:
            return r.json()
        elif r.status_code == 404:
            raise ClashRoyaleAPIClanNotFound(self.clan_tag)
        else:
            if(r.json()['reason'] == 'accessDenied'):
                raise ClashRoyaleAPIAuthenticationError(r.json()['message'])
            else:
                raise ClashRoyaleAPIError(r.content)
```

In order for crtools to work in the cloud (amazon, google, etc.). However with the new version of the API and the new verison of CRTools I'm not sure where we should put this. Do you think we can add this as an option? The idea is that the "proxy" parameter is present, the following should be added to all requests:
```
        proxyDict = {
            "http": os.environ.get('FIXIE_URL', ''),
            "https": os.environ.get('FIXIE_URL', '')
        }
        r = requests.get(self.baseurl + endpoint,
                         headers=self.headers, proxies=proxyDict)
```

In my case I'm using FIXIE as a proxy but this should work with any other service regardless.

**Comment by AaronTraas** [comment]
@waclock Sure... I can add this. I'm not sure how to test it on my end. 

The minor complication is that this code is mostly generated from openapi-generator. Ideally, I'd have to add it into a file that I blacklist from getting stomped on.

One of the few files that I've got custom code in is configuration.py, and that has some proxy stuff in it. I may actually be able to do proxy stuff in crtools, by adding config options to the crtools.ini

There's 2 settings in Configuration:
```
        self.proxy = None
        """Proxy URL
        """
        self.proxy_headers = None
        """Proxy headers
        """
```

I won't be able to take a look at this today, but if you can tinker around and figure out what these would need to be filled with, I can make options in crtools so you can set them in the config file.

**Comment by AaronTraas** [comment]
@waclock - added 2 options to .ini file in 2.7.6 of crtools:

```
[API]
# Proxy URL -- URL for proxy server, if needed
proxy=https://my-proxy.com

# Proxy headers -- custom headers for proxy if needed
proxy_headers=headers
```

That should work... let me know if it doesn't. I'm exclusively using HTTPS for this, so just include the HTTPS proxy.

**Comment by AaronTraas** [comment]
Closing issue due to lack of response. If the proposed solution doesn't work, feel free to re-open.
